language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t georgelil/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true georgelil/docker-react npm run test